---
version: 1
enabled: true
plugins:
  job_runtime:
    enabled: true
  static_hosting:
    pr-preview:
      metadata:
        name: "Preview"
      path: dist
    test-doverage
      metadata:
        name: "Test Coverage"
      path: coverage/lcov
