name: Preview

on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE.md'
      - 'CREDIT.md'
      - 'CHANGELOG.md'
      - 'devnotes.md'
      - '.editorconfig'
    branches:
      - main

jobs:
  pr-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Build App
        run: |
          if [ -e yarn.lock ]; then
          yarn install --ignore-optional --frozen-lockfile
          yarn build
          elif [ -e package-lock.json ]; then
          npm ci --no-optional
          npm run build
          else
          npm i --no-optional
          npm run build
          fi
      - name: Run Stoat Action
        uses: stoat-dev/stoat-action@v0
        if: always()

